### ISSUE TITLE
Read and reference US DoE building standards for UWG

### ISSUE THREAD

**Issue by saeranv** [chriswmackey/UWG_Python#1]
Write a translation or develop a new method to read US DoE building read from DOERefBlds excel files, and translate it for UWG inputs.

DOERefBlds here:
https://github.com/hansukyang/UWG_Matlab/tree/master/data/DOERefBuildings 

Currently this is handled by the following files in the original UWG:
https://github.com/hansukyang/UWG_Matlab/blob/master/RefDOE.mat
https://github.com/hansukyang/UWG_Matlab/blob/master/readDOE.m

**Comment by chriswmackey** [comment]
@saeranv ,
As we discussed, you are assigned to this one and you can work your way through it at your own pace as it is separate from the main engine.  Let me know if you hit any snags.

**Comment by saeranv** [comment]
@chriswmackey 

Hit the first snag! 

It looks like matlab has a native way to read the .xlsx files with the DOE reference buildings ([here](https://github.com/saeranv/UWG_Python/blob/52ea9d9f61c239d3ca776976de2d7d9c8a7faf72/UWG/readDOE.py#L69)).

I've never had to read xlsx before, but after doing some googling it looks like we'd have to download an additional python module in order to read xlsx. Which starts getting messy for other users. Is there a way to read xlsx that I've overlooked?

If not, I can convert the xlsx sheets to csv files and read that. There will be about 64 sheets I'd have to convert to csv (16 buildings x 4 sheets each).

-S

**Comment by chriswmackey** [comment]
@saeranv ,
Sorry for the late response here.
As you say, there are 2 possible ways around this issue and I trust your judgement with which one you think is best.  Just to give you a sense of the pros and cons of each:

1) You can covert everything over to CSV and, while I know that this creates a lot of files, the nice part about this is that anyone will be able to run your script from any machine as long as it has python (no need to have excel installed; no need to run the script on a Windows system; and no need to install any additional Python modules).  I prefer this method but you have gotten deeper into the script than I have so, if you think it's better to go another route, feel free to run with it.

2) You could use an python excel-reading module like xlrd.  The downside of this is that anyone else who wants to run the script would have to also install this module, making it less accessible than the csv option.  Still, once this module is installed, we could still run the script on any platform we want (no need to have excel installed or be on a Windows system).  However, storing all of the data in .xlsx format means that we probably need excel to read the files outside of the script, making it less accessible on other systems.

**Comment by saeranv** [comment]
@chriswmackey 

I agree with your points. Option 1 looks the best, especially from a user perspective. I'll convert the sheets to CSV and read that.

**Comment by chriswmackey** [comment]
Excellent job @saeranv !
